conftest and helm cli added
raballew/cli-base pull request #1
Opened 2020-12-01 08:41 UTC by ckavili

2020-12-01 11:37 UTC, raballew requested changes
I would like to use the OpenShift mirror as much as possible.

2020-12-01 11:37 UTC, raballew commented on Containerfile
> +    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && \
Can we use https://mirror.openshift.com/pub/openshift-v4/clients/ instead?

2020-12-02 10:54 UTC, ckavili commented on Containerfile
> +    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && \
of course we can :)

2020-12-02 12:19 UTC, raballew approved these changes
/lgtm

2020-12-02 12:20 UTC, merged